- name: restore settings.php from backup
  copy:
    src: "{{ backups }}/settings.php"
    dest: "{{ siteroot }}/settings.php"
    owner: "{{ drupaluser }}"
    group: "{{ drupaluser }}"
    mode: 0644
    remote_src: yes