
- name: save settings.php
  copy:
    src: "{{ siteroot }}/settings.php"
    dest: "{{ backups }}/settings.php"
    owner: "{{ drupaluser }}"
    group: "{{ drupaluser }}"
    mode: 0644
    remote_src: yes

- name: remove the old drupalroot
  command: rm -rf {{ sitename }}
  args:
    chdir: /local/drupal