---
# tasks file for refresh-db-files
- include_vars: ../../vars.yml

- name: Taking database dump of {{ sitename }} {{ tier }}
  shell: drush sql-dump --result-file={{ backup_directory }}/{{ backup_dbfile }}
  args: 
    chdir: "{{ siteroot }}"

- name: Taking archive copy of {{ sitename }} {{ tier }}
  command: tar --exclude=settings.php -czvf {{ backup_directory }}/{{ backup_file }}  {{ sitename }}
  args: 
    chdir : /local/drupal