---
# tasks file for import-db
- include_vars: ../../vars.yml

- name: Import {{ sitename }} {{fhost }} database to {{ tier }}
  shell: 
    cmd: cd {{ siteroot }} && drush sql-cli < {{ backup_directory }}/{{ backup_dbfile }}
  register: import
- debug: msg={{ import }}

- name: Clear drush cache
  shell:
    cmd: drush cc all
    chdir: "{{ siteroot }}"     
  register: clear
- debug: msg={{ clear }}
