---
- name: Provision Instance
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    
    - ec2_key_name: aws-devops-key
    - ec2_instance_type: t2.micro
    - ami: ami-55ef662f
    - exact_ec2_count: '{{ exact_ec2_count }}'

  tasks:
  - name: provision a new ec2 instance
    ec2: 
      key_name: "{{ ec2_key_name }}"
      group: "{{ sg_group }}"
      region: "{{ aws_region }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ami }}"
      wait: yes
      exact_count: "{{ exact_ec2_count }}"
      count_tag:
        Count: "{{ project_name }}"
      instance_tags:
        Name: "{{ project_name }}"
        Count: "{{ project_name }}"
      vpc_subnet_id: "{{ subnet_id }}"
      assign_public_ip: yes
    register: ec2

  - debug: msg={{ ec2 }}

  - name: Wait for SSH to come up
    wait_for:
      port: 22
      host: "{{ item.public_ip }}"
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.tagged_instances }}"

  - name: pause to let cloud init to complete
    pause:
      seconds: 30

  - name: build group of instances
    add_host:
      name: "{{ item.public_dns_name }}"
      groups: web
      ansible_user: ec2-user
      ansible_host: "{{ item.public_ip }}"
    with_items: "{{ ec2.tagged_instances }}"



  



































