---
# tasks file for refresh-files

- include_vars: ../../vars.yml

- name: Taking archive copy of {{ sitename }} {{ tier }}
  command: tar --exclude=settings.php -czvf {{ backup_directory }}/{{ backup_file }}  {{ sitename }}
  args: 
    chdir : /local/drupal
    
    


