---
# tasks file for sync-files
- include_vars: ../../vars.yml

- name: Backup drupal core directory on {{ tier }}
  archive:
    path: "{{ drupalroot }}"
    dest: "{{ backups }}/{{ sitecopy }}-{{ date }}.tgz"
    owner: "{{ drupaluser }}"
    mode: 0644
  poll: 5
  
- name: Extract archive copy of {{ sitename }} from {{ fhost }} to {{ tier }}
  unarchive:
    src: "{{ backup_directory }}/{{ backup_file }}"
    dest: "{{ drupalroot }}/../"
    remote_src: yes
  register: extract
  poll: 5

- debug: msg={{ extract }}

- name: Clear drush cache
  shell:
    cmd: drush cc all
    chdir: "{{ siteroot }}"
  register: clear

- debug: msg={{ clear }}
    
